responses = [
  '.{handle} Hey, hows that resolution going?'
  'Hey {handle}, hows that resolution going?'
  '.{handle} Any updates on this?'
  'Any updates on this, {handle}?'
  '.{handle} Bumping this resolution to see how it\'s been going!'
  '.{handle} How\'d this turn out?'
  'How\'d this turn out, {handle}?'
  '.{handle} What\'s been going on with this resolution?'
  'What\'s been going on with this resolution, {handle}?'
  '.{handle} Pinging to see how the resolution went! :)'
  'Pinging to see how the resolution went {handle}! :)'
  '.{handle} did you get this resolution done?'
  'Did you get this resolution done, {handle}?'
  '.{handle} how did this resolution go?'
  'How did this resolution go, {handle}?'
  'Hey, {handle} hows this resolution come along?'
  'Hey hows this resolution come along, {handle}?'
  'Yo {handle}, how\'s this resolution going? Still time to accomplish it!'
  '.{handle} Hey, just checking in how this resolution is going ^__^'
  'Hey, just checking in how this resolution is going {handle} ^__^'
  '.{handle} Swinging by to ask how this resolution is going! You still got some time to finish it!'
  'Swinging by to ask how this resolution is going! You still got some time to finish it {handle}!'
  'Hey {handle}, just wanted to see if you\'ve kept up with this resolution!'
  'Hey just wanted to see if you\'ve kept up with this resolution {handle}!'
  '.{handle}, hope all is well, seeing how you\'re keeping up with the resolution!'
  'Hope all is well {handle}, seeing how you\'re keeping up with this resolution!'
  '.{handle} any updates on this?'
  'Any updates on this {handle}?'
  '.{handle} bumping this resolution to see how it\'s been going!'
  'Bumping this resolution to see how it\'s been going {handle}!'
  '.{handle} how\'d this turn out?'
  'How\'d this turn out, {handle}?'
  'Hey, {handle}! This was your new year\'s resolution last year!'
  'What\'s been going on with this resolution, {handle}?'
  '.{handle}, what\'s been going on with this resolution?'
  '.{handle} did you get this resolution done?'
  '.{handle} don\'t give up on this resolution!'
  'Don\'t give up on this resolution {handle}!'
]

module.exports =
  responses: responses
